version: "3"
services:
  node:
    image: "node:lts-alpine"
    working_dir: /
    network_mode: bridge
    volumes:
      - /docker_data/pairdrop/app:/home/node/app
    command: ash -c "npm i && npm run start:prod"
    restart: unless-stopped
    ports:
      - "7110:3000"
