version: "3"
services:
  node:
    image: "node:lts-alpine"
    working_dir: /app
    network_mode: "bridge"
    volumes:
      - /docker_data/pairdrop/app:/home/node/app
    command: ash -c "npm i && npm run start:prod"
    restart: unless-stopped
    ports:
      - "7110:3000"
  coturn_server:
    image: "coturn/coturn"
    restart: always
    network_mode: "bridge"
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf
    #you need to copy turnserver_example.conf to turnserver.conf and specify domain, IP address, user and password
